### ISSUE TITLE
Images overlapping on first load

### ISSUE THREAD

**Issue by ghost** [philipbjorge/Infinite-Social-Wall#11]
When the page loads at first, the first entries with images are being overlapped by other posts. When the user scrolls down (and the page loads more items), new posts containing images don't get overlapped. You can check it out here: http://www.jfmamjjasond.de

As I investigated (http://stackoverflow.com/questions/8622906/isotope-overlapping-images), this is because of isotope is being loaded when the **page renders**. As referred in the stackoverflow-post, this should be loaded on `$(window).load`.

But I have no clue, where to change it in the code. Should this be done in the `jquery.infinitesocialwall.js`?

**Comment by philipbjorge** [comment]
Thanks for researching this - I added a fix for this which I tested on my own site which showed the issue.

**Comment by ghost** [comment]
Awesome - works like a charm! Thanks for providing us with this tool :-)

**Comment by philipbjorge** [comment]
I'm glad you're finding a use for it - There will be more updates to come, as I (and others) come up with new features (and find bugs I'm sure :D).
