### ISSUE TITLE
AJAX Update

### ISSUE THREAD

**Issue by jkreimmer** [philipbjorge/Infinite-Social-Wall#15]
Hi! You did a great job with this tool!! thank you!

I wonder if there is a way to update the stream with AJAX every x minutes ?
I found a function in jquery.infinitesocialwall.js which seems to add the items not stored in the database but does this just once, 

Could you help me to know how can I do this ? have you planned a feature like this ?

thanks again.

**Comment by philipbjorge** [comment]
Here's how you would do it...

Add the following to the end of jquery.infinitesocialwall.js - This will call the update script every 60 seconds and add any new content to the wall.

```
setInterval(function() {
    $("#new-content").load('get_stream.php?p=update', function() {
        $container.isotope('insert', $(this).children('.social-item'));
        $("time").timeago();
    });
}, 60 * 1000);
```

This won't function how you expect it until you modify line 102 in get_stream.php

```
$feed->set_cache_duration(59); // 59 second cache
```

The RSS feeds are by default cached for 15 minutes to prevent taxing the server's your grabbing them from.

Setting small polling intervals can adversely affect performance, but I have no benchmarks or general guidelines.

I'm closing this, but reopen it if you have issues.
